name: Release changelog generator for Meilisearch
author: curquiza <clementine@meilisearch.com>
description: This GitHub Actions creates the release changelogs and open the PR on the meilisearch/core team repository.
inputs:
  milestones_name:
    description: 'The title of the Milestones (vX.Y.Z)'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MILESTONES_NAME: ${{ inputs.milestones_name }}
    GH_TOKEN: ${{ inputs.github_token }}
branding:
  icon: file
  color: purple
